version: '2'

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.5.0
        command: launch manager
        environment:
         - CALIPER_PROJECTCONFIG=config/caliper-onchain.yaml
         - CALIPER_BIND_SUT=ethereum:latest
         - CALIPER_BENCHCONFIG=config/caliper-benchconfig.yaml
         - CALIPER_NETWORKCONFIG=config/caliper-networkconfig.json 
         - CALIPER_FLOW_SKIP_INSTALL=true
        volumes:
         - ./BusinessLogic-benchmarks:/hyperledger/caliper/workspace
        networks:
        - BCFL

networks:
  BCFL:
    external: true