test:
  name: Reputation Management 
  description: Reputation Management performance test
  workers:
    type: local
    number: 1
  rounds:
   - label: warm-up (ignore results)
     txNumber: 1000
     rateControl:
       type: maximum-rate
       opts:
         tps: 370
         step: 20
         sampleInterval: 10
         includeFailed: true
     workload:
       module: workload/calculateObjectiveReputation.js
       arguments:
        contract: ManageReputation
        num: 1
   - label: second round
     txNumber: 1000
     rateControl:
       type: maximum-rate
       opts:
         tps: 370
         step: 20
         sampleInterval: 10
         includeFailed: true
     workload:
       module: workload/calculateObjectiveReputation.js
       arguments:
        contract: ManageReputation
        num: 2
   - label: second round
     txNumber: 1000
     rateControl:
       type: maximum-rate
       opts:
         tps: 370
         step: 20
         sampleInterval: 10
         includeFailed: true
     workload:
       module: workload/calculateObjectiveReputation.js
       arguments:
        contract: ManageReputation
        num: 3


    
    