version: '3.7'

services:
  client:
    hostname: client
    image: fl-node
    #network_mode: "host"
    entrypoint: /root/client_register.sh
    deploy:
      replicas: $CLIENTS
    environment:
      - IPFS_API=/dns/host.docker.internal/tcp/5001
      - CONTRACT=$CONTRACT
      - TASK=$TASK
      - PRIVATEKEY=$PRIVATEKEY
    volumes:
    
      - '../../../federated_learning/regular_user/data_manipulation/data:/root/dataset'
      - ../../../artifacts-zk/contracts/$ABI_FILE.sol/$ABI.json:/root/abi.json


    extra_hosts:
      - "host.docker.internal:host-gateway"

  
networks:
  default:
    external:
      name: BCFL

