test:
  name: Business logic 
  description: Business logic performance test
  workers:
    type: local
    number: 1
  rounds:
   - label: warm-up (ignore results)
     txNumber: 800
     rateControl:
       type: maximum-rate
       opts:
         tps: 201
         step: 5
         sampleInterval: 10
         includeFailed: true
     workload:
       module: workload/publishTask.js
       arguments:
        contract: BusinessLogic
        num: 1
   - label: second round
     txNumber: 800
     rateControl:
       type: maximum-rate
       opts:
         tps: 201
         step: 5
         sampleInterval: 10
         includeFailed: true
     workload:
       module: workload/publishTask.js
       arguments:
        contract: BusinessLogic
        num: 2
   - label: second round
     txNumber: 800
     rateControl:
       type: maximum-rate
       opts:
         tps: 201
         step: 5
         sampleInterval: 10
         includeFailed: true
     workload:
       module: workload/publishTask.js
       arguments:
        contract: BusinessLogic
        num: 3
  